introduction/urls.py
from django.urls import path
from . import views

app_name = "introduction"

urlpatterns = [
    path('', views.profile, name="profile"),
]

myblog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('introduction/', include('introduction.urls')),
    path('', views.main,name = 'main'),
    path('posts/', include('posts.urls')),
    path('accounts/', include('allauth.urls')),
    ]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from .views import *
 
app_name ="posts"
urlpatterns = [
    path('new/', new, name="new"),
    path('create/', create, name="create"),
    path('', main, name="main"),
    path('<int:id>', show, name="show"),
    path('update/<int:id>/', update, name="update"),
    path('delete/<int:id>/', delete, name="delete"),
    path('<int:post_id>/create_comment', create_comment, name="create_comment"),
    path('<int:post_id>/post_like', post_like, name="post_like"),
    path('like_list', like_list, name="like_list")
]

introduction/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models
from django.contrib.auth.models import User

class Post(models.Model):
    title = models.CharField(max_length= 50, null=False)
    writer = models.ForeignKey(User, on_delete = models.CASCADE, null=True)
    content = models.TextField()
    view_count = models.IntegerField(default = 0)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    image = models.ImageField(upload_to='images/', null=True)
    like_user_set = models.ManyToManyField(User, blank=True, related_name='like_user_set', through='Like')

    @property
    def like_count(self):
        return self.like_user_set.count()
    

class Comment(models.Model):
    content = models.TextField()
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)


class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = (('user', 'post'))

posts/forms.py
from django.forms import ModelForm
from .models import Post

class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = [
            'title',
            'content',
            'image',
        ]
        labels = {
            'title': ('제목'),
            'content': ('내용'),
            'image': ('이미지'),
        }
        help_texts = {
            'title': ('제목을 입력해주세요.'),
            'content': ('내용을 입력해주세요.'),
        }


    def save(self, **kwargs):
        post = super().save(commit=False)
        post.user = kwargs.get('user', None)
        post.save()
        return post

introduction/views.py
from django.shortcuts import render

# Create your views here.
def profile(request):
    return render(request, 'introduction/profile.html')

myblog/views.py
from django.shortcuts import render

# Create your views here.
def main(request):
    return render(request, 'main.html')

posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Post, Comment
from django.contrib.auth.decorators import login_required
from .forms import PostForm

@login_required

def new(request):
    form = PostForm()
    return render(request, 'posts/new.html', {'form':form})


def create(request):
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            form.save(user = request.user)
        return redirect('posts:main')

        # title = request.POST.get('title')
        # writer = request.user
        # content = request.POST.get('content')
        # image = request.FILES.get('image')
        # Post.objects.create(title=title, content=content, image=image, writer=writer)

def main(request):
    posts = Post.objects.all()
    return render(request, 'posts/main.html', {'posts':posts})

def show(request, id):
    post = Post.objects.get(pk=id)
    A = post.view_count
    A = A + 1
    post.view_count = A
    post.save() 
    all_comments = post.comments.all().order_by('-created_at')
    return render(request, 'posts/show.html', {'post': post, 'comments': all_comments})

def update(request,id):
    post = get_object_or_404(Post,pk=id)
    if request.method == "POST":
        post.title = request.POST['title']
        post.content = request.POST['content']
        post.image = request.FILES.get('image')
        post.save()
        return redirect('main')
    return render(request,'posts/update.html',{'post':post})


def delete(request, id): 
	post = get_object_or_404(Post, pk=id) 
	post.delete()
	return redirect("posts:main")


def create_comment(request, post_id):
    if request.method == "POST":
        post = get_object_or_404(Post, pk=post_id)
        current_user = request.user
        comment_content = request.POST.get('content')
        Comment.objects.create(content=comment_content, writer=current_user, post=post)
    return redirect('posts:show', post.pk)


def post_like(request, post_id):
    post = get_object_or_404(Post, pk=post_id)

    if request.user in post.like_user_set.all():
        post.like_user_set.removed(request.user)
    else:
        post.like_user_set.add(request.user)

    if request.GET.get('redirect_to')=='show':
        return redirect('posts:show', post_id)
    else:
        return redirect('posts:main')


@login_required
def like_list(request):
    likes = request.user.like_set.all()
    return render(request,'posts/like_list.html',{'likes':likes})

introduction/templates/introduction/profile.html
{% extends 'base.html' %}
{% block content %}
<h1>profile page</h1>
{% endblock %}

myblog/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <title>Hello, world!</title>
    <link rel="stylesheet" href="{% static 'css/project.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css"/>
  </head>
  <body>
    {% include 'shared/_navbar.html' %}
    <div class="container">
    {% block content %}

    {% endblock %}
    </div>  

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

myblog/templates/main.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1>main page</h1>
<img src="{% static 'images/image 01.jpg' %}" alt="프로필 이미지">
{% endblock %}

myblog/templates/shared/_navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'main' %}">main</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'introduction:profile' %}">profile <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'posts:new' %}">새글쓰기</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'posts:main' %}" tabindex="-1">글목록</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'posts:like_list' %}" tabindex="-1">좋아요목록</a>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Account</a>
        <div class="dropdown-menu">
          {% if user.is_authenticated %} {# 유저가 로그인 중이면 #}
            <a class="dropdown-item" href="{% url 'account_logout' %}" class="nav-link">Logout</a>
            <a class="dropdown-item" href="{% url 'account_change_password' %}">Change PW</a>
          {% else %}
            <a class="dropdown-item" href="{% url 'account_login' %}" class="nav-link">Login</a>
            <a class="dropdown-item" href="{% url 'account_signup' %}" class="nav-link">Sign Up</a>
          {% endif %}
        </div>
      </li>
    </ul>    
  </nav>

  
  

posts/templates/posts/like_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
        {% if user.is_authenticated %}
            <h1>좋아요한 글 목록</h1>
            <div class="row">
            {% for like in likes %}
                <div class="col-md-4 col-12">
                    <div class="card" style="width:18rem; margin-top:20px;">
                        <div class="card-body">
                            <h5 class="card-title">{{ like.post.title }}</h5>
                            <p>조회수: {{like.post.view_count }}</p>
                            <a href="{% url 'posts:show' like.post.id %}" class="btn btn-primary">상세보기</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
            </div>
        {% else %}
            <h3>로그인 후 이용이 가능합니다.</h3>
            <a href="{% url 'account_login'%}" class="btn btn-warning">로그인</a>
            <a href="{% url 'account_signup'%}" class="btn btn-warning">회원가입</a>
        {% endif %}
</div>
{% endblock %}

posts/templates/posts/main.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% if user.is_authenticated %}
<div class="container">
    <h1>글 목록입니다.</h1>
    <a class="btn btn-outline-dark" href="{% url 'posts:new' %}">새글쓰기</a>
    <div class="row">
        {% for post in posts %}
        <div class="col-md-4 col-12">
            <div class="card" style="width: 18rem; margin-top: 20px;">
                <div class="card-body">
                    <h5 class="card-title">{{ post.title }}</h5>
                    <p class="card-text">{{ post.content }}</p>
                    <p>{{ post.created_at }}</p>
                    <p>조회수: {{ post.view_count }}</p>
                    <a href="{% url 'posts:post_like' post.id %}">
                            {% if user in post.like_user_set.all %}
                                <i class="fas fa-heart"></i>
                            {% else %}
                                <i class="far fa-heart"></i>
                            {% endif %}
                    </a>
                    <a href="{% url 'posts:show' post.pk %}" class="btn btn-primary">상세보기</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% else %}
    <h3>로그인 후 이용이 가능합니다</h3>
    <a href="{% url 'account_login' %}" class="btn btn-warning">로그인</a>
    <a href="{% url 'account_signup' %}" class="btn btn-warning">회원가입</a>
{% endif %}
{% endblock %}

posts/templates/posts/new.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1>
    새로운 글 작성하기
    </h1>
    <form action="{% url 'posts:create' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <!-- <div class="form-group">
            <label>글 제목</label>
            <input type="text" class="form-control" name="title">
        </div>
        <div class="form-group">
            <label>글 내용</label>
            <textarea class="form-control" name="content"></textarea>
        </div>
        <input type="file" name="image" accept="image/*"> -->
        <input type="submit" value="글 작성" class="btn btn-outline-primary">
    </form>
</div>
{% endblock %}

posts/templates/posts/post_form.html
<div class="container">
    <form action="#" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }} # 각 필드가 paragraph 행으로 렌더링
        <input type="submit" value="확인" class="btn btn-primary">
    </form>
</div>

posts/templates/posts/show.html
{% extends 'base.html' %}
{% block content %}
<h1>상세보기 페이지</h1>
<h3>글 제목 : {{ post.title }} </h3><br>
<h3>글 내용 : {{ post.content }} </h3><br>
{% if post.writer %}
	{% if post.writer.username == 'user' %}
		<h3>작성자 : {{ post.writer.last_name }} {{ post.writer.first_name }}</h3><br>
	{% else %}
		<h3>작성자 : {{ post.writer }}</h3><br>
	{% endif %}
{% else %}
	<h3>작성자 : 알 수 없음</h3>
{% endif %}

<h3>작성 시각 : {{ post.created_at }} </h3><br>
<h3>수정 시각 : {{ post.updated_at }} </h3><br>
<h3>조회수: {{post.view_count }}</h3><br>  
{% if post.image %}
	 <img src ="{{ post.image.url }}" alt="">
{%  endif %}

{% if user == post.writer %}
	<a href="{% url 'posts:update' post.pk %}" class="btn btn-primary">수정하기</a>
	<a href = "{% url 'posts:delete' post.pk %}" class="btn btn-danger">삭제하기</a>
{% endif %}

<div class="container mt-5">
	<a href="{% url 'posts:post_like' post.id %}?redirect_to=show">
			{% if user in post.like_user_set.all %}
				<i class="fas fa-heart"></i>
			{% else %}
				<i class="far fa-heart"></i>
			{% endif %}
	</a>
</div>


<div class="container mt-5">
	<form class="form-row" action="{% url 'posts:create_comment' post.id %}" method="POST">
		{% csrf_token %}
		<textarea class="form-control col-11 mr-2" name="content"
placeholder="댓글 내용 입력..."></textarea>
		<input type="submit" class="btn btn-primary" value="확인">
	</form>
</div>

<div class="container mt-5 mb-5">
	{% for comment in comments %}
	<div class="card">
		<div class="card-body">
			{% if comment.writer.username == 'user' %}
			<b>{{ comment.writer.last_name }}{{ comment.writer.first_name }}
				{% else %}
				<b>{{ comment.writer }}</b> {% endif %} : {{ comment.content }}</br>
				<small>{{ comment.created_at }}</small>
		</div>
	</div>
	{% endfor %}
</div>
{% endblock %}

posts/templates/posts/update.html
{% extends 'base.html' %}
 {% block content %}
 <div class="container"> 
	<h1> 수정하기 </h1> 
	<form action="{% url 'posts:update' post.id %}" method="POST" enctype="form-data"> 
		{% csrf_token %} 
		<div class="form-group">
			 <label>글 제목</label> 
			<input type="text" class="form-control" name="title" value = "{{ post.title }}"> 
		</div>
		 <div class="form-group">
			 <label>글 내용</label>
			 <textarea class="form-control" name="content"> {{ post.content }} </textarea>
         </div>
        <input type="file" name="image">
 		<input type="submit" value="글 수정" class="btn btn-outline-primary">
	 </form> 
</div>
 {% endblock %}